name: Setup Superviseur
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-superviseur:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Superviseur
        uses: ./
        with:
          version: v0.1.0-alpha.3
      - name: Verify Superviseur
        run: superviseur --version
